### ISSUE TITLE
implement swaggerui endpoint

### ISSUE THREAD

**Issue by michaelgloeckner** [onecx-apps/onecx-chat#2]
the onecx-chat-svc should provide openapi interface to see rest endpoints and its request structure

**Comment by lmitlaender** [comment]
Swagger UI can be found under domain:port/docs in local development under http://127.0.0.1:8001/docs
![image](https://github.com/onecx-apps/onecx-chat/assets/24322646/b123d55f-fe22-45bf-94f2-b1320aa9015b)

FastAPI furthermore implements ReDoc as a Swagger UI alternative, which can be found under /redoc
![image](https://github.com/onecx-apps/onecx-chat/assets/24322646/abd70130-7203-4d97-baa4-51342cc8f360)
